name: nmea
description: An extensible NMEA0183 parser, which also supports validating the checksum. Useful for reading data from GPS devices and other sensors.
homepage: https://github.com/ricardoboss/dart_nmea
repository: https://github.com/ricardoboss/dart_nmea
issue_tracker: https://github.com/ricardoboss/dart_nmea/issues

version: 3.3.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: any
  strict: any
